In [4]:
import numpy as np
a1=np.array([2.0,3,4.0],dtype=np.int8)

In [8]:
print(a1.dtype)
print(a1.ndim)
print(a1.shape)
print(a1.itemsize)
print(a1.size)


int8
1
(3,)
1
3


In [14]:
ar1=np.arange(27) #[0,27]
print(ar1)
ar2=np.arange(1,10,0.3)
print(ar2)
ar3=np.linspace(1,117,30)
print(ar3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
[  1.   5.   9.  13.  17.  21.  25.  29.  33.  37.  41.  45.  49.  53.
  57.  61.  65.  69.  73.  77.  81.  85.  89.  93.  97. 101. 105. 109.
 113. 117.]


In [19]:
np_list=[]
np_list.append(np.zeros((3,4,5),dtype=np.int8))
np_list.append(np.full((3,4,5),132,dtype=np.int16))
np_list.append(np.eye(5,k=1))
np_list.append(np.eye(5,k=0))
np_list.append(np.diag(np_list[2],k=1)) #진단시 사용
for np1 in np_list:
    print(np1)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]

 [[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]

 [[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1.]


In [ ]:
b1=np.ones_like(a3)
b2=np.zeros_like(a3)
b3=np.full_like(a3)
print(b1)


In [ ]:
print(a2)
a3=np.arange(9).reshape((3,3))
print(a3)
c1=a2+a3
c2=a2-a3
c3=a2/a3
print(c1,c2,c3)