In [20]:
import numpy as np
a1=np.array([2.0,3,4.0],dtype=np.int8)

In [25]:
print(a1.dtype)
print(a1.ndim)
print(a1.shape)
print(a1.itemsize)
print(a1.size)


int8
1
(3,)
1
3


In [26]:
ar1=np.arange(27) #[0,27]
print(ar1)
ar2=np.arange(1,10,0.3)
print(ar2)
ar3=np.linspace(1,117,30)
print(ar3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
[  1.   5.   9.  13.  17.  21.  25.  29.  33.  37.  41.  45.  49.  53.
  57.  61.  65.  69.  73.  77.  81.  85.  89.  93.  97. 101. 105. 109.
 113. 117.]


In [27]:
np_list=[]
np_list.append(np.zeros((3,4,5),dtype=np.int8))
np_list.append(np.full((3,4,5),132,dtype=np.int16))
np_list.append(np.eye(5,k=1))
np_list.append(np.eye(5,k=0))
np_list.append(np.diag(np_list[2],k=1)) #진단시 사용
for np1 in np_list:
    print(np1)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
[[[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]

 [[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]

 [[132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]
  [132 132 132 132 132]]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1.]


In [30]:
b1=np.ones_like(ar3)
b2=np.zeros_like(ar3)
# b3=np.full_like(ar3)
print(b1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [31]:
print(ar2)
a3=np.arange(9).reshape((3,3))
print(a3)
c1=ar2+ar3
c2=ar2-ar3
c3=ar2/ar3
print(c1,c2,c3)

[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8 6.1
 6.4 6.7 7.  7.3 7.6 7.9 8.2 8.5 8.8 9.1 9.4 9.7]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[  2.    6.3  10.6  14.9  19.2  23.5  27.8  32.1  36.4  40.7  45.   49.3
  53.6  57.9  62.2  66.5  70.8  75.1  79.4  83.7  88.   92.3  96.6 100.9
 105.2 109.5 113.8 118.1 122.4 126.7] [   0.    -3.7   -7.4  -11.1  -14.8  -18.5  -22.2  -25.9  -29.6  -33.3
  -37.   -40.7  -44.4  -48.1  -51.8  -55.5  -59.2  -62.9  -66.6  -70.3
  -74.   -77.7  -81.4  -85.1  -88.8  -92.5  -96.2  -99.9 -103.6 -107.3] [1.         0.26       0.17777778 0.14615385 0.12941176 0.11904762
 0.112      0.10689655 0.1030303  0.1        0.09756098 0.09555556
 0.09387755 0.09245283 0.09122807 0.09016393 0.08923077 0.0884058
 0.08767123 0.08701299 0.08641975 0.08588235 0.08539326 0.08494624
 0.08453608 0.08415842 0.08380952 0.08348624 0.08318584 0.08290598]
